**Data Preprocessing**

In [ ]:
#Importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [ ]:
tf.__version__

'2.8.0'

In [ ]:
#Importing datasets
df = pd.read_csv('/content/drive/MyDrive/Machine Learning A-Z (Codes and Datasets)/Part 8 - Deep Learning/Section 39 - Artificial Neural Networks (ANN)/Python/Churn_Modelling.csv')
x = df.iloc[:,3:-1].values
y = df.iloc[:,-1].values

In [ ]:
print(x)
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


In [ ]:
#Missing Values
#Categorical Encoding(Label Encoding on Gender Column)
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:,2] = le.fit_transform(x[:,2])
print(x)
print('\n\n')
#One hot Encoder on Geography column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder="passthrough")
# all remaining colunms that were not specified in tarnsformers will automatically be passed through
x= np.array(ct.fit_transform(x))
# x= ct.fit_transform(x)
print(x)
# if we run this cell again and again , hotencoding will be added on 0th column again

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]



[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [ ]:
#Train split test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)   #random, if not specified, then on every new exection, the train and test datasets will give different values

In [ ]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)
print(x_train)
print(x_test)

[[-0.99850112  1.71490137 -0.57273139 ... -1.55337352  0.97725852
   0.42739449]
 [ 1.00150113 -0.58312392 -0.57273139 ... -1.55337352 -1.02327069
  -1.02548708]
 [-0.99850112  1.71490137 -0.57273139 ...  0.64376017  0.97725852
  -0.94479772]
 ...
 [ 1.00150113 -0.58312392 -0.57273139 ...  0.64376017  0.97725852
  -0.14096853]
 [ 1.00150113 -0.58312392 -0.57273139 ...  0.64376017  0.97725852
   0.01781218]
 [-0.99850112  1.71490137 -0.57273139 ...  0.64376017 -1.02327069
  -1.15822478]]
[[ 1.00150113 -0.58312392 -0.57273139 ...  0.64376017  0.97725852
  -0.05360571]
 [ 1.00150113 -0.58312392 -0.57273139 ...  0.64376017 -1.02327069
  -0.58392685]
 [ 1.00150113 -0.58312392 -0.57273139 ... -1.55337352  0.97725852
  -0.16685331]
 ...
 [-0.99850112 -0.58312392  1.74601919 ... -1.55337352  0.97725852
   1.0669965 ]
 [-0.99850112  1.71490137 -0.57273139 ...  0.64376017  0.97725852
   1.13101314]
 [-0.99850112  1.71490137 -0.57273139 ...  0.64376017  0.97725852
  -0.88790165]]


**Building the ANN**

In [ ]:
#Initializing the ANN
ann = tf.keras.models.Sequential() #seq class is taken from models module of the keras library of tensorflow

In [ ]:
#Adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units = 6,activation='relu')) 
#add is used for adding hidden layers
#keras = Keras acts as an interface for the TensorFlow library.
#Dense = Fully connected neural network

In [ ]:
#Adding second hidden layer
ann.add(tf.keras.layers.Dense(units = 6,activation='relu')) 

In [ ]:
#Adding the output layer
ann.add(tf.keras.layers.Dense(units = 1,activation='sigmoid')) #sigmoid is used for 0 or 1(Exited Column), else if more than two categories in output use 'SOFTMAX' func

**Training the ANN**

In [ ]:
#Compiling the ANN
ann.compile(optimizer="adam", loss="binary_crossentropy" , metrics= ['accuracy']) #if output==binary(binary_crossentropy) , else output==categorical_crossentropy


In [ ]:
#Training the ANN on the training set
ann.fit(x_train,y_train,batch_size=32, epochs=100) #epochs==iterations,batch_size==batch of neurons

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5625 - accuracy: 0.7429
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4701 - accuracy: 0.7974
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4451 - accuracy: 0.8002
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4318 - accuracy: 0.8044
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4228 - accuracy: 0.8080
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4128 - accuracy: 0.8161
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4020 - accuracy: 0.8211
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3909 - accuracy: 0.8295
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3810 - accuracy: 0.8341
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3734 - accura

**Making the predictions and evaluating the model**
Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France  
Credit Score: 600   
Gender: Male        
Age: 40 years old             
Tenure: 3 years             
Balance: 60000        
Number of Products: 2     
Does this customer have a credit card? Yes
Is this customer an Active Member: Yes
Estimated Salary: $ 50000
So, should we say goodbye to that customer?


In [ ]:
print(ann.predict(sc.transform([[1,0,0, 600, 1, 40,3,60000,2,1,1,50000]])) > 0.5) #0.5 is the threshold value to classify into 0 or 1

[[False]]


In [ ]:
# Predicting the Test set results
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]
[[1532   53]
 [ 210  205]]


0.8685